name: Latexmk

on: push

jobs:
  build-pdfs:
    # Name the Job
    name: Build PDFs
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Latexmk
        uses: ianmcloughlin/latexmk-action@version6

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public